### ISSUE TITLE
mp3 or mp4 feature

### ISSUE THREAD

**Issue by diyaa59** [diyaa59/youtube-dl-mp4-mp3#1]
# **Add a new code to download mp3 audio out of a video.**
steps:
1. Add functions to the script and read the second argument provided by the user to the script.
1.1 if second argument has a value of "mp3" run a function that downloads only audio in mp3 format.
1.2 if second argument has a value of "mp4" run a function that downloads best video + best audio combined.

**Comment by mowglixx** [comment]
## Suggestion:
Default to "mp4" with a conditional branch that says 

```
if(!arg2){
   arg2= "mp4"
}
```

something like this, I'm not well versed on `bash` syntax

**Comment by diyaa59** [comment]
I think it is more like
```bash
if [[ $2 != mp4 ]]; then
    action
fi
```
